# Generated by Django 5.0.4 on 2024-05-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_colaborador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cantidad_permisos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='dias_vacaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='dias_vacaciones_disponibles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
