# Generated by Django 5.0.4 on 2024-06-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_colaborador_cantidad_permisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='es_administrativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='es_almacen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='es_vendedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tiene_acceso_total',
            field=models.BooleanField(default=False),
        ),
    ]
